<div align="center"><img src="./images/about1.jpg" width="100%"></div>
<h1>Az alapítvány története</h1>
<p>A Nebuló XXI. Alapítvány az örömteli tanulásért, 2003-ban született meg. Az a hit hozta létre, hogy lehet öröm a tanulás. Hogy lehet izgalmas kaland új meg új ismeretekre szert tenni. Lehet az örömnek kimeríthetetlen forrása egy mesterség értő művelése, a folyamat, ahogy az anyag engedelmesen a kéz alá simul, életre kél.</p>
<p>Az Alapítvány a dunaújvárosi Pentelei Molnár János Szakiskolában született, amelynek működtetője és fenntartója volt. Az iskola kiemelten foglalkozik tehetséggondozással ill. vállalja hátrányos helyzetű diákok oktatását, nevelését is. Az iskola vezetősége hisz abban, hogy a megértés, az elfogadás, a közösség ereje kinevel olyan mesterembereket, akik értékes részei a társadalomnak, és megtalálják ebben a saját egyedi helyüket. Az intézmény kézműves tanműhelyből lett szakiskola. A kézművesség kreativitásra és játékos szemléletre épül.</p>
<p>Új kihívás a XXI. század technokrata szellemének megfelelni és ebben embernek maradni. Egyre nagyobb szerepe van ebben a játéknak. A Nebuló Alapítvány a játékpedagógia elkötelezett híve és terjesztője. A Nebuló Játékegyetem felnőtteket tanít arra, hogyan lehet az iskolában készségeket fejleszteni a játékokkal. Iskola-játéktár programunkkal minél több iskolába szeretnénk eljuttatni játékokat és inspirációt, tudást ezek pedagógiai felhasználásához.</p>
<p>A játék és a játékosság fontossága hozta létre a Társasjátékok Ünnepét is, melyet 2012 óta szervez meg az Alapítvány, hogy minél szélesebb rétegekhez tudja eljuttatni azt az üzenetet, hogy játszani nem csak jó, de hasznos is, hiszen a modern társasjátékok kínálatában rengeteg fejlesztő játék van, amely egy örömszerző tevékenység közben fejleszti a képességeket és készségeket.</p>
<br />
<div align="center"><img src="./images/about2.jpg" width="100%"></div>
<h1>Az alapítvány kuratóriuma</h1>
<p>Az Alapítvány kuratóriumát felnőttképzésben, tehetséggondozásban és oktatásban aktívan résztvevő pedagógusok és szakemberek működtetik. Kuratóriumi tagságuk mindennapi munkájuk elismerése és folytatása is egyben.</p>
<p>A kuratórium elnöke: <strong>Schiff Ágnes</strong><br />
Felnőttképzések és önismereti tanfolyamok szervezője, kézműves klubok vezetője. Ezen tevékenységeiben kiemelten foglalkozott hátrányos helyzetű diákokkal, hiperaktív gyerekekkel; kreativitással próbálta önmaguk, értékeik megismerését segíteni. 1991-ben megalapítja az Aranytű Szakiskolát, amely 2010 óta Pentelei Molnár János Szakiskola néven működik. 2005-ben Várhegyi György Díjat kap évtizedes munkásságáért.</p>
<p>A Nebuló Iskola-játéktár referense: <strong>Aczél Zoltán</strong><br />
A dunaújvárosi játékklub megalapítója. Eredeti foglalkozása könyvrestaurátor, de 1990-től, saját műhelyének beindítása mellett játékfejlesztéssel is foglalkozott. Hét éves svájci és németországi élete folyamán több társasjátéka jelent meg külföldön. 2001-ben megalapítja a Gémklub Kft.-t, mely nem csak társasjátékok forgalmazásával foglalkozik, de célul tűzte ki a magyarországi játékfejlesztés felkarolását, erősítését.</p>
<p>A Játékegyetem referense: <strong>Jesztl József</strong><br />
Tehetséggondozó pedagógus és játékismereti előadó. Végzettsége szerint szociálpedagógus, de folyamatosan bővíti ismereteit – képesített rekreációs sportoktató, szociokultúrális animátor, mese-terapeuta. Számos sport- és játékesemény szervezésében vesz részt. Rendszeresen vesz részt hazai és külföldi, társasjátékokkal kapcsolatos továbbképzéseken, illetve itthon maga is tart játékpedagógiai képzéseket („Játékismeret a tehetséggondozásban”). Aczél Zoltánnal karöltve fejlesztik és terjesztik hazánkban a társasjátékpedagógiát, 2011-ben közös projektjüknek, a Játéktár programnak a Nemzeti Erőforrások Minisztériuma volt a fővédnöke.</p>
<br />
<div align="center"><img src="./images/about3.jpg" width="100%"></div>
<h1>Legfontosabb eredményeink</h1>
<p>2011-ben Jesztl József, tehetséggondozó szociálpedagógus, aki a Tudor Alapítvány Józsefvárosi Tehetséggondozó Műhely vezetőjeként fejlesztette ki a társasjáték-pedagógia elvét, közös projektbe kezdett az Alapítvány vezetőjével, Aczél Zoltánnal. A Játéktár program nem csak a társasjáték-pedagógiát szerette volna minél szélesebb körökkel megismertetni, de jó pár iskolába egy „társasjáték-pedagógia kezdőcsomagot” is eljuttatott. A projekt fővédnöke a Nemzeti Erőforrások Minisztériuma volt, és a programban az iskolák pályázati úton vetettek részt.</p>
<p>2015-ben már negyedik alkalommal szervezte meg az Alapítvány a Társasjátékok Ünnepét, mely az oktatási rendszer kereteiből kilépve, szélesebb rétegek – és nem csak gyermekek, hanem egész családok és felnőttek – számára mutatta be a társasjátékok világát.</p>
<p>A Társasjátékok Ünnepe ad minden évben otthont a Társasjátékok Olympiájának, amely az ország több városában működő társasjátékos klubok játékosainak ad lehetőséget, hogy a klubokban lebonyolított selejtezőkből kikerülő legjobb csapatok egy döntő keretében mérhessék össze tudásukat.</p>